<?php

declare(strict_types=1);

return [
    'countriesUrl' => $_ENV['COUNTRIES_URL'],
    'currenciesUrl' => $_ENV['CURRENCIES_URL'],
    'currenciesApiAccessKey' => $_ENV['EXCHANGE_RATES_API_KEY'],
    'calculationPrecision' => 10,
    'outputPrecision' => 2,
    'euCodes' => [
        'AT',
        'BE',
        'BG',
        'CY',
        'CZ',
        'DE',
        'DK',
        'EE',
        'ES',
        'FI',
        'FR',
        'GR',
        'HR',
        'HU',
        'IE',
        'IT',
        'LT',
        'LU',
        'LV',
        'MT',
        'NL',
        'PO',
        'PT',
        'RO',
        'SE',
        'SI',
        'SK',
    ],
];